### ISSUE TITLE
Getting cannot read property token when IP is not whitelisted

### ISSUE THREAD

**Issue by mohak-cf** [cashfree/cashfree-sdk-nodejs#31]
Error thrown by SDK: 
{"level":"error","message":"error validating bank details, \"TypeError: Cannot read property 'token' of undefined\\n    at Auth.authorize (/Users/mohak.gupta/curefit/payment-service/node_modules/cashfree-sdk/lib/auth/index.js:81:40)\\n    at process._tickCallback (internal/process/next_tick.js:68:7)\"","timestamp":"2020-09-03 18:22:41","iID":"CF-LP00286.local","pID":35728,"rID":"e2b3f034-7361-40c9-8074-05ed0306419c"}

Actual API response:
{
  "status": "ERROR",
  "subCode": "403",
  "message": "IP not whitelisted"
}

**Comment by theavijitsarkar** [comment]
Remove all IP whitelisting and try
